# Appium Server Config
appium.server.url=http://127.0.0.1:4723

# Device Capabilities
platform.name=Android
device.name=Android Emulator
automation.name=UiAutomator2
app.path=../plansphere/build/app/outputs/flutter-apk/app-debug.apk
auto.grant.permissions=true
no.reset=false

# Wait Timeouts
implicit.wait.seconds=10
explicit.wait.seconds=15

# Output Report Folders
reports.base.dir=reports
excel.report.path=reports/Excel/Automation_Test_Report.xlsx
excel.passed.path=reports/Excel/Passed_Test_Cases.xlsx
excel.failed.path=reports/Excel/Failed_Test_Cases.xlsx
excel.summary.path=reports/Excel/Execution_Summary.xlsx

html.report.path=reports/HTML/execution-report.html
html.dashboard.path=reports/HTML/dashboard.html
html.trends.path=reports/HTML/trends.html

json.report.path=reports/JSON/execution-results.json
summary.report.path=reports/Summary/summary.md

screenshots.dir=reports/Screenshots
logs.dir=reports/Logs
history.dir=reports/history
